spring:
  application:
    name: CartService
  r2dbc:
    url: r2dbc:mysql://localhost:3306/retailer_db?serverTimezone=Asia/Kolkata&useLegacyDatetimeCode=false
    username: testing
    password: tiger
    initialize-schema: always
    show-sql: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,actuator

logging:
  level:
    root: INFO
    com.example.cartservice: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000ms
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost



